<b>Q Find max. product of two integeres in an array.

Case 1: Positive integer array

In [5]:
import numpy as np
from array import *

In [23]:
arr = np.array([1,20,30,44,5,56,57,5,1,5,6,15,12,35,58,19,21,32,12])

def findMaxProductPosIntegers(arrPos):
    num1 = 0
    num2 = 0
    for num in arrPos:
        if num>num1:
            num2 = num1
            num1 = num
        elif num > num2:
            num2 = num
    print(num1, num2)
    return(num1*num2)
findMaxProductPosIntegers(arr)

58 57


3306

Case 2: Positive or Negative integer array

In [36]:
arr = np.array([1,-20,30,44,5,56,-57,5,1,5,6,15,12,-35,58,19,21,-88,12])

def findMaxProdAnyIntegers(arr):
    num1 = 0
    num2 = 0
    num3 = 0
    num4 = 0
    
    for num in arr:
        if num>num1:
            num2 = num1
            num1 = num
        elif num>num2:
            num2 = num
        if num<num3:
            num4 = num3
            num3 = num
        elif num<num4:
            num4 = num
    return(max(num1*num2, num3*num4))

findMaxProdAnyIntegers(arr)

5016

### Q1222. Queens That Can Attack the King

<img src = 'https://assets.leetcode.com/uploads/2019/10/01/untitled-diagram.jpg'>

On an 8x8 chessboard, there can be multiple Black Queens and one White King.

Given an array of integer coordinates queens that represents the positions of the Black Queens, and a pair of coordinates king that represent the position of the White King, return the coordinates of all the queens (in any order) that can attack the King.

* Input: queens = [[0,1],[1,0],[4,0],[0,4],[3,3],[2,4]], king = [0,0]

* Output: [[0,1],[1,0],[3,3]]

Explanation:

* The queen at [0,1] can attack the king cause they're in the same row.

* The queen at [1,0] can attack the king cause they're in the same column. 

* The queen at [3,3] can attack the king cause they're in the same diagnal. 

* The queen at [0,4] can't attack the king cause it's blocked by the queen at [0,1]. 

* The queen at [4,0] can't attack the king cause it's blocked by the queen at [1,0]. 

* The queen at [2,4] can't attack the king cause it's not in the same row/column/diagnal as the king.

Constraints:
* 1 <= queens.length <= 63
* queens[i].length == 2
* 0 <= queens[i][j] < 8
* king.length == 2
* 0 <= king[0], king[1] < 8
* At most one piece is allowed in a cell.

In [32]:
queens = [[0,1],[1,0],[4,0],[0,4],[3,3],[2,4]]
king = [0,0]
result = []
directions = [-1,0,1]

for dx in directions:
    for dy in directions:
        if dx == 0 and dy ==0:
            continue

        x = int(king[0])
        y = int(king[1])
        while x + dx >= 0 and x + dx <8 and y+dy >=0 and y + dy <8:
            x+= dx
            y+= dy
            if [x,y] in queens:
                result.append([x,y])
                break
print(result)

[[0, 1], [1, 0], [3, 3]]


### 1823. Find the Winner of the Circular Game

<img src = 'https://assets.leetcode.com/uploads/2021/03/25/ic234-q2-ex11.png' width = "50%">

There are n friends that are playing a game. The friends are sitting in a circle and are numbered from 1 to n in clockwise order. More formally, moving clockwise from the ith friend brings you to the (i+1)th friend for 1 <= i < n, and moving clockwise from the nth friend brings you to the 1st friend.

The rules of the game are as follows:

* Start at the 1st friend.
* Count the next k friends in the clockwise direction including the friend you started at. The counting wraps around the circle and may count some friends more than once.
* The last friend you counted leaves the circle and loses the game.
* If there is still more than one friend in the circle, go back to step 2 starting from the friend immediately clockwise of the friend who just lost and repeat.
* Else, the last friend in the circle wins the game.
* Given the number of friends, n, and an integer k, return the winner of the game.

Input: n = 5, k = 2

Output: 3

Explanation: Here are the steps of the game:
1. Start at friend 1.
2. Count 2 friends clockwise, which are friends 1 and 2.
3. Friend 2 leaves the circle. Next start is friend 3.
4. Count 2 friends clockwise, which are friends 3 and 4.
5. Friend 4 leaves the circle. Next start is friend 5.
6. Count 2 friends clockwise, which are friends 5 and 1.
7. Friend 1 leaves the circle. Next start is friend 3.
8. Count 2 friends clockwise, which are friends 3 and 5.
9. Friend 5 leaves the circle. Only friend 3 is left, so they are the winner.

In [61]:
class Solution:
    def findTheWinner(self, n: int, k: int) -> int:
            arr = np.arange(1,6,1)
            start = 1

            while len(arr) != 0:
                print(len(arr))
                print(arr)
                try:
                    arr = np.delete(arr, start)
                    start += 1
                    if start>= len(arr):
                        start = start-len(arr)
                except:
                    break
        
sol = Solution()
sol.findTheWinner(n = 5, k = 2)

5
[1 2 3 4 5]
4
[1 3 4 5]
3
[1 3 5]
2
[3 5]
1
[3]


In [46]:
arr = np.arange(1,6,1)
len(np.delete(arr, 2))
len(arr)

5